= DSSAT for Docker

== Layout
....
dssat-docker/
  + dssat47/       (build directory)
  + src/           (source directory)
    | Dockerfile   (dssat-csm-build Dockerfile)
    + dssat-csm/   (github DSSAT source)
  | README.adoc
  | Dockerfile     (dssat-csm Dockerfile)
....

== Build Steps

1. Download/Update dssat-csm source from github
2. Build the *dssat-csm-build* docker image. This should not be pushed to docker hub.

 cd src
 docker build -t dssat-csm-build .


3. Run the *dssat-csm-build* docker image from the *dssat-docker* directory.

 cd ..
 docker run --rm -it -v ${PWD}:/app dssat-csm-build

4. Build DSSAT

 rm -rf /app/dssat47 ## BE CAREFUL!!!
 cd /app/src/dssat-csm/build
 rm -rf * ## BE CAREFUL!!!!
 cmake -DCMAKE_INSTALL_PREFIX=/app/dssat47 -DCMAKE_BUILD_TYPE=RELEASE ..
 make && make install
 exit

5. Dockerize DSSAT from the *dssat-docker* directory

 docker build -t dssat-csm .

== Running DSSAT (single point)

1. Change to the directory with your experimental files (XFile, etc.)

2. Run dssat-docker

 docker run --rm -v ${PWD}:/data -w /data dssat-csm A <xfile name>

 or

 docker run --rm -v ${PWD}:/data -w /data dssat-csm B <batch file name>
