= DSSAT for Docker

== Layout
....
dssat-docker/
  + custom/
    | Dockerfile
    | <your DSSAT source directory>
  + official/
    | Dockerfile
  | README.adoc
....

== Official Build Steps

IMPORTANT: There is no real reason to build your own official dssat-docker. This is published on Docker Hub under `dssat/dssat-csm`.

 cd dssat-docker/official
 docker build -t dssat-csm-official .

== Custom DSSAT Build Steps

1. Copy or checkout your custom dssat-csm code under the custom directory. *This is a docker restriction.*

2. Run `docker build`
By default, the `Dockerfile` looks for the `dssat-csm-os` directory. You can change this by adding `--build-arg DSSAT_SRC_DIR=<directory name>`

 docker build -t custom-dssat-build .

or

 docker build -t custom-dssat-build --build-arg DSSAT_SRC_DIR=dssat47 .

NOTE: The dssat-csm-os does *NOT* include crop experiments, default soil data, and weathers. If you need these, you should checkout https://github.com/dssat/dssat-csm-data and copy the files from there into the Data directory prior to building.

== Running DSSAT (single point)

1. Change to the directory with your experimental files (XFile, Soil, Weather, etc. unless included as stated above)

2. Run dssat-docker

 docker run --rm -v ${PWD}:/data -w /data dssat-csm A <xfile name>

 or

 docker run --rm -v ${PWD}:/data -w /data dssat-csm B <batch file name>
